/**
 * Demo jobs shown when both JSearch and MongoDB cache fail.
 * Keep these realistic so UI looks correct.
 */
const DEMO_JOBS = [
  {
    jobId: 'demo-1',
    title: 'Frontend Developer',
    company: 'Stripe',
    location: 'San Francisco, CA (Remote)',
    salary: '$120K–$160K/year',
    description: 'We are looking for a skilled Frontend Developer to join our payments infrastructure team. You will build beautiful, fast, and accessible user interfaces using React, TypeScript, and modern web standards. Requirements: 3+ years React experience, TypeScript proficiency, experience with testing frameworks (Jest, Cypress), strong CSS/Tailwind skills, GraphQL knowledge preferred.',
    requiredExperience: 3,
    skills: ['React', 'TypeScript', 'GraphQL', 'Tailwind CSS', 'Jest'],
    jobType: 'Full-time',
    workMode: 'Remote',
    url: 'https://stripe.com/jobs',
    source: 'demo',
  },
  {
    jobId: 'demo-2',
    title: 'Full Stack Engineer',
    company: 'Vercel',
    location: 'Remote',
    salary: '$130K–$170K/year',
    description: 'Join Vercel to build the platform that powers the modern web. As a Full Stack Engineer you will work on the Next.js deployment pipeline, Edge Network, and developer dashboard. You should have 2+ years experience with Node.js, React, PostgreSQL, and cloud infrastructure (AWS or GCP). Experience with Rust is a plus.',
    requiredExperience: 2,
    skills: ['Node.js', 'React', 'PostgreSQL', 'AWS', 'Next.js'],
    jobType: 'Full-time',
    workMode: 'Remote',
    url: 'https://vercel.com/careers',
    source: 'demo',
  },
  {
    jobId: 'demo-3',
    title: 'React Developer',
    company: 'Figma',
    location: 'New York, NY',
    salary: '$115K–$145K/year',
    description: 'Figma is hiring a React Developer to build our next-generation design tools. You\'ll work closely with designers to implement pixel-perfect, performant UI components. Required: React 18+ expertise, TypeScript, Redux or Zustand, canvas/WebGL experience a big plus, 2+ years professional experience.',
    requiredExperience: 2,
    skills: ['React', 'TypeScript', 'Redux', 'WebGL', 'CSS'],
    jobType: 'Full-time',
    workMode: 'Hybrid',
    url: 'https://figma.com/careers',
    source: 'demo',
  },
  {
    jobId: 'demo-4',
    title: 'Backend Engineer',
    company: 'PlanetScale',
    location: 'Remote',
    salary: '$140K–$180K/year',
    description: 'PlanetScale is building the world\'s most scalable database platform. We need a Backend Engineer experienced in Go or Python, distributed systems, MySQL internals, and Kubernetes. 4+ years backend experience required. You will design APIs, improve performance, and contribute to our open-source Vitess tooling.',
    requiredExperience: 4,
    skills: ['Go', 'Python', 'MySQL', 'Kubernetes', 'Distributed Systems'],
    jobType: 'Full-time',
    workMode: 'Remote',
    url: 'https://planetscale.com/careers',
    source: 'demo',
  },
  {
    jobId: 'demo-5',
    title: 'Software Engineer',
    company: 'Linear',
    location: 'Remote',
    salary: '$125K–$165K/year',
    description: 'At Linear we build the issue tracker loved by the world\'s best software teams. Looking for a Software Engineer with strong TypeScript, React, Node.js, and PostgreSQL skills. You care deeply about code quality, product design, and developer experience. 2-5 years experience. Experience with WebSockets and real-time collaboration is a plus.',
    requiredExperience: 2,
    skills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'WebSockets'],
    jobType: 'Full-time',
    workMode: 'Remote',
    url: 'https://linear.app/careers',
    source: 'demo',
  },
  {
    jobId: 'demo-6',
    title: 'Frontend Engineer',
    company: 'Loom',
    location: 'Austin, TX (Hybrid)',
    salary: '$110K–$140K/year',
    description: 'Loom is the video messaging platform that helps teams communicate asynchronously. Join our Frontend team to build the recording, playback, and sharing experience used by millions. Required: React, TypeScript, 2+ years experience, video/media APIs experience preferred, excellent CSS skills, Jest testing.',
    requiredExperience: 2,
    skills: ['React', 'TypeScript', 'CSS', 'Jest', 'Video APIs'],
    jobType: 'Full-time',
    workMode: 'Hybrid',
    url: 'https://loom.com/careers',
    source: 'demo',
  },
];

module.exports = DEMO_JOBS;
